---
apiVersion: v1
kind: Service
metadata:
  name: mediagram-svc-headless
  namespace: default
  labels:
    app.kubernetes.io/name: mediagram
    app.kubernetes.io/instance: myapp-svc-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 4369
      targetPort: epmd
      protocol: TCP
      name: epmd
  selector:
    app.kubernetes.io/name: mediagram
    app.kubernetes.io/instance: myapp-node